networkIdentifier: "arbitrum-sepolia"
gateway:
  url: "http://127.0.0.1:8030/"
networkProvider:
  url: <network-provider>
indexerOptions:
  address: "0xf56b5d582920E4527A818FBDd801C0D80A394CB8"
  mnemonic: "famous aspect index polar tornado zero wedding electric floor chalk tenant junk"
  url: "http://test-indexer.xyz"
subgraphs:
  maxBlockDistance: 1000000
  networkSubgraph:
    url: "https://gateway-arbitrum.network.thegraph.com/api/<api-key>/subgraphs/id/3xQHhMudr1oh69ut36G2mbzpYmYxwqCeU6wwqyCDCnqV"
  epochSubgraph:
    url: "http://test-url.xyz"
  tapSubgraph:
    url: "https://gateway-arbitrum.network.thegraph.com/api/<api-key>/subgraphs/name/graphprotocol/scalar-tap-arbitrum-sepolia"
transactionMonitoring:
  gasIncreaseTimeout: 240000
  gasIncreaseFactor: 1.2
  baseFeePerGasMax: 100000000000
  maxTransactionAttempts: 0
tapAddressBook:
  "11155111":
    TAPVerifier: "0xf56b5d582920E4527A818FBDd801C0D80A394CB8"
    AllocationIDTracker: "0xf56b5d582920E4527A818FBDd801C0D80A394CB8"
    Escrow: "0xf56b5d582920E4527A818FBDd801C0D80A394CB8"
dai:
  contractAddress: "0x4e8a4C63Df58bf59Fef513aB67a76319a9faf448"
  inject: false
