apiVersion: v1
kind: Service
metadata:
  name: indexer-service
spec:
  type: NodePort
  selector:
    app: indexer-service
  ports:
    - name: indexer-service
      protocol: TCP
      port: 80
      targetPort: 80
