apiVersion: v1
kind: Pod
metadata:
  name: shell
  namespace: default
spec:
  volumes:
    - name: nfs-shared
      persistentVolumeClaim:
        claimName: nfs-shared
        readOnly: false
  containers:
  - image: graph-node-debug
    name: shell
    command:
      - /bin/sh
      - "-c"
      - "sleep infinity"
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - name: nfs-shared
        mountPath: /var/lib/graph
    env:
      - name: ethereum
        valueFrom:
          configMapKeyRef:
            name: ethereum-networks
            key: networks
      - name: PGHOST
        valueFrom:
          secretKeyRef:
            name: postgres-credentials
            key: host
      - name: PGUSER
        valueFrom:
          secretKeyRef:
            name: postgres-credentials
            key: user
      - name: PGPASSWORD
        valueFrom:
          secretKeyRef:
            name: postgres-credentials
            key: password
      - name: PGDATABASE
        value: graph
      - name: node_id
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
  restartPolicy: Always
