apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-service
spec:
  selector:
    matchLabels:
      app: indexer-service
  replicas: 1
  template:
    metadata:
      labels:
        app: indexer-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "7300"
    spec:
      # Temporary: Allow to pull private Docker images
      imagePullSecrets:
        - name: docker-registry
      containers:
        - name: indexer-service
          image: indexer-service-image
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 600m
          ports:
            - name: http
              containerPort: 7600
            - name: metrics
              containerPort: 7300
          env:
            - name: INDEXER_SERVICE_MNEMONIC
              valueFrom:
                secretKeyRef:
                  name: indexer-mnemonic
                  key: mnemonic
            - name: INDEXER_SERVICE_PORT
              value: "7600"
            - name: INDEXER_SERVICE_ETHEREUM
              value: https://kovan.alchemyapi.io/jsonrpc/demo/
            - name: INDEXER_SERVICE_GRAPH_NODE_QUERY_ENDPOINT
              value: http://query-node.default.svc.cluster.local/
            - name: INDEXER_SERVICE_GRAPH_NODE_STATUS_ENDPOINT
              value: http://query-node.default.svc.cluster.local/index-node/graphql
            - name: INDEXER_SERVICE_NETWORK_SUBGRAPH_ENDPOINT
              value: https://gateway.network.thegraph.com/network
            - name: INDEXER_SERVICE_POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: host
            - name: INDEXER_SERVICE_POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user
            - name: INDEXER_SERVICE_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password
            - name: INDEXER_SERVICE_POSTGRES_DATABASE
              value: indexer
            - name: INDEXER_SERVICE_WALLET_SKIP_EVM_VALIDATION
              value: "true"
            - name: INDEXER_SERVICE_FREE_QUERY_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: free-query-auth-token
                  key: token
